version: '3.1'

services:

  identityserver:
    build: ./identityServer/
    container_name: identityServer
    environment:
      - ASPNETCORE_ENVIRONMET=Development
    ports:
      - "5000:80"
    depends_on:
      - database

  fileserver:
    build: fileServer/docker
    container_name: fileServer
    volumes:
      - ./FileServer/:/usr/src/fileserver
      - dashboard-fileserver-data:/usr/src/fileserver/stored/user_Files
    ports:
      - "5001:80"
    links:
      - identityserver:localhost

  dashboard:
    build: ./dashboard/docker
    container_name: dashboard
    volumes:
      - ./dashboard/:/app/
    ports:
      - "4200:4200"
    links:
      - identityserver:localhost
      - fileserver:localhost

  testclient:
    build: ./testClient/docker
    container_name: testclient
    volumes:
      - ./testclient/:/app/
    ports:
      - "4201:4201"
    links:
      - identityserver:localhost
      - fileserver:localhost

  database:
    build: ./database/docker
    container_name: database
    volumes:
      - ./database/mysql:/mysql
      - ./database/init-db:/docker-entrypoint-initdb.d
      - dashboard-database-data:/var/lib/mysql/data
    ports:
      - "3306:3306"
    environment:
      -  MYSQL_RANDOM_ROOT_PASSWORD=yes

volumes:
  dashboard-database-data:
    driver: local

  dashboard-fileserver-data:
    driver: local