FROM mysql/mysql-server:5.7
COPY config/my.cnf /etc/my.cnf



#RUN ls config
#ADD config/docker-entrypoint.sh /opt/docker-entrypoint.sh

#RUN chmod 755 /*.sh
#CMD ["/bin/bash", "/opt/docker-entrypoint.sh"]
